(() => {
  if (!location.pathname.toLowerCase().includes('khajuraho')) return;
  const style = document.createElement('style');
  style.textContent = `.rs-toolkit{padding:88px 12%;background:#f7f1e5}.rs-toolkit h2{font:600 clamp(38px,4vw,60px)/1 'Playfair Display';letter-spacing:-2px;margin:0}.rs-toolkit .lead{max-width:650px;color:#60736b;line-height:1.65}.rs-tool-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-top:35px}.rs-tool-card{background:#fffdf5;padding:24px;border-top:3px solid #d85e39}.rs-tool-card b{font-size:10px;letter-spacing:1.3px;color:#d85e39}.rs-tool-card h3{font:600 25px 'Playfair Display';margin:12px 0 8px}.rs-tool-card p{font-size:13px;color:#60736b;line-height:1.6;margin:0 0 13px}.rs-tool-card a,.rs-print{display:inline-block;color:#183b35;font-size:12px;font-weight:700;border-bottom:1px solid #183b35}.rs-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:18px}.rs-actions button{border:0;background:#183b35;color:#fff;padding:11px 14px;font:700 12px 'DM Sans';cursor:pointer}.rs-actions button:hover{background:#d85e39}.rs-tool-note{margin:16px 0 0;padding:14px;background:#e2ebc0;color:#183b35;font-size:13px;line-height:1.5}.rs-extra{margin-top:16px;padding:22px;background:#183b35;color:#fff;display:flex;gap:20px;justify-content:space-between;align-items:center}.rs-extra h3{font:600 28px 'Playfair Display';margin:0 0 7px}.rs-extra p{max-width:680px;margin:0;color:#dce6de;font-size:13px;line-height:1.6}.rs-extra a{background:#dae88a;color:#183b35;padding:12px 15px;font-weight:700;font-size:12px;white-space:nowrap}@media(max-width:850px){.rs-toolkit{padding:70px 8%}.rs-tool-grid{grid-template-columns:1fr}.rs-extra{display:block}.rs-extra a{display:inline-block;margin-top:15px}}`;
  document.head.append(style);
  const note=document.querySelector('#rsToolNote');
  const messages={family:'Family plan: 2 days choose karein. Day 1 sirf Western Group; Day 2 Eastern/Jain aur Southern temples. Raneh/Panna ko extra day mein rakhein.',heritage:'Heritage plan: Kandariya, Lakshmana, Vishvanatha, Devi Jagadambi, Chitragupta aur Varaha ke liye Day 1 par enough time rakhein. Day 2 Jain group aur Southern group complete karein.',budget:'Budget plan: Western Group/town centre ke paas stay, Day 1 walking aur Day 2 ke liye ek planned auto/cab route rakhein. Panna safari optional planned expense hai.'};
  document.querySelectorAll('[data-style]').forEach(button=>button.addEventListener('click',()=>{note.textContent=messages[button.dataset.style]}));
  document.querySelector('.rs-print')?.addEventListener('click',()=>window.print());
})();
