(() => {
  if (!location.pathname.toLowerCase().includes('mandu')) return;
  const before = document.querySelector('#before-you-go');
  if (!before || document.querySelector('.rs-toolkit')) return;
  const style = document.createElement('style');
  style.textContent = `.rs-toolkit{padding:88px 12%;background:#f7f1e5}.rs-toolkit h2{font:600 clamp(38px,4vw,60px)/1 'Playfair Display';letter-spacing:-2px;margin:0}.rs-toolkit .lead{max-width:650px;color:#60736b;line-height:1.65}.rs-tool-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-top:35px}.rs-tool-card{background:#fffdf5;padding:24px;border-top:3px solid #d85e39}.rs-tool-card b{font-size:10px;letter-spacing:1.3px;color:#d85e39}.rs-tool-card h3{font:600 25px 'Playfair Display';margin:12px 0 8px}.rs-tool-card p{font-size:13px;color:#60736b;line-height:1.6;margin:0 0 13px}.rs-tool-card a,.rs-print{display:inline-block;color:#183b35;font-size:12px;font-weight:700;border-bottom:1px solid #183b35}.rs-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:18px}.rs-actions button{border:0;background:#183b35;color:#fff;padding:11px 14px;font:700 12px 'DM Sans';cursor:pointer}.rs-actions button:hover{background:#d85e39}.rs-tool-note{margin:16px 0 0;padding:14px;background:#e2ebc0;color:#183b35;font-size:13px;line-height:1.5}.rs-extra{margin-top:16px;padding:22px;background:#183b35;color:#fff;display:flex;gap:20px;justify-content:space-between;align-items:center}.rs-extra h3{font:600 28px 'Playfair Display';margin:0 0 7px}.rs-extra p{max-width:680px;margin:0;color:#dce6de;font-size:13px;line-height:1.6}.rs-extra a{background:#dae88a;color:#183b35;padding:12px 15px;font-weight:700;font-size:12px;white-space:nowrap}@media(max-width:850px){.rs-toolkit{padding:70px 8%}.rs-tool-grid{grid-template-columns:1fr}.rs-extra{display:block}.rs-extra a{display:inline-block;margin-top:15px}}`;
  document.head.append(style);
  before.insertAdjacentHTML('beforebegin', `<section class="rs-toolkit"><p class="eyebrow">PLAN LIKE A LOCAL</p><h2>Stay, eat & spend<br>with less confusion.</h2><p class="lead">Mandu ko sirf monuments ki list se plan mat karo. Central Mandu mein raho, ek connected route follow karo aur sunset ke baad unnecessary driving mat karo.</p><div class="rs-tool-grid"><article class="rs-tool-card"><b>WHERE TO STAY</b><h3>Stay close to Mandu</h3><p><strong>Central Mandu / Main Road:</strong> first-time travellers ke liye best base. Royal group aur restaurants paas rahenge. <strong>Outside Mandu:</strong> tabhi choose karein jab aapke paas apna vehicle aur extra time ho.</p><a target="_blank" rel="noopener" href="https://www.google.com/maps/search/?api=1&query=hotels+in+Mandu+Madhya+Pradesh">Find stays in Maps ↗</a></article><article class="rs-tool-card"><b>FOOD BY ROUTE</b><h3>Eat where you are</h3><p><strong>Morning:</strong> central Mandu. <strong>Lunch:</strong> royal-group visit ke baad Mandu mein. <strong>Dinner:</strong> Roopmati Pavilion se wapas aane ke baad stay ke paas. Isse dark mein extra driving nahi hogi.</p><a target="_blank" rel="noopener" href="https://www.google.com/maps/search/?api=1&query=restaurants+in+Mandu+Madhya+Pradesh">Find food in Maps ↗</a></article><article class="rs-tool-card"><b>SMART BUDGET</b><h3>Keep a buffer</h3><p>Monument tickets, full-day cab, water aur snacks ke liye alag buffer rakhein. Driver se pehle hi clear karein ki royal group aur Roopmati route dono cover honge.</p><a target="_blank" rel="noopener" href="https://www.mptourism.com/destination-mandu.php">Check official Mandu details ↗</a></article></div><div class="rs-actions"><button data-style="family">Family plan</button><button data-style="heritage">Heritage plan</button><button data-style="budget">Budget plan</button><button class="rs-print">Save / print plan</button></div><p class="rs-tool-note" id="rsToolNote">Apna travel style choose karke Mandu ka best adjustment dekhein.</p><div class="rs-extra"><div><h3>Have one extra morning?</h3><p>Extra time mein Sagar Talao ya quiet viewpoints rakhein, lekin main royal route ko disturb mat karein. Monsoon mein weather aur local road advice pehle check karein.</p></div><a target="_blank" rel="noopener" href="https://www.google.com/maps/search/?api=1&query=Sagar+Talao+Mandu">Open Sagar Talao in Maps ↗</a></div></section>`);
  const note = document.querySelector('#rsToolNote');
  const messages = {
    family: 'Family plan: 2-day plan choose karein. Day 1 par royal group, Day 2 par Baz Bahadur, Rewa Kund aur Roopmati Pavilion rakhein. Dhoop mein midday rest zaroor lein.',
    heritage: 'Heritage plan: Jahaz Mahal, Champa Baoli, Hindola Mahal, Jami Masjid, Hoshang Shah\'s Tomb aur Ashrafi Mahal ko Day 1 par proper time dein. Day 2 ki sunset route alag rakhein.',
    budget: 'Budget plan: Central Mandu mein stay, local breakfast aur ek shared/full-day vehicle route rakhein. Ek hi din mein far-away detours jodne se cab cost aur time dono badhenge.'
  };
  document.querySelectorAll('[data-style]').forEach(button => button.addEventListener('click', () => { note.textContent = messages[button.dataset.style]; }));
  document.querySelector('.rs-print')?.addEventListener('click', () => window.print());
})();
